from __future__ import annotations

from typing import Any


def render_markdown_report(result: dict[str, Any]) -> str:
    """Generate a clean Markdown report from the phase acceptance result dict."""
    verdict = result.get("verdict", "unknown").upper()
    verdict_emoji = "✅" if verdict in ("ACCEPT", "PASS") else "❌" if verdict in ("ROLLBACK", "BLOCKED") else "⚠️"

    lines = [
        f"# AgentLab Phase Acceptance Report: {result.get('phase_id', 'Unknown')}",
        "",
        "## 1. Executive Summary",
        "",
        f"- **Verdict**: {verdict_emoji} **{verdict}**",
        f"- **Recommended Next Action**: `{result.get('recommended_next_action', 'None')}`",
        f"- **Rationale**: {result.get('rationale', 'No rationale provided.')}",
        "",
        "## 2. Scope Inspection",
        "",
        f"- **Drift Detected**: {result.get('scope_status', {}).get('has_drift', False)}",
        f"- **Unauthorized Edits**: {result.get('scope_status', {}).get('has_violations', False)}",
    ]

    # Changed files
    changed_files = result.get("scope_status", {}).get("changed_files") or []
    if changed_files:
        lines.append("- **Changed Files**:")
        for f in changed_files:
            lines.append(f"  - `{f}`")
    else:
        lines.append("- **Changed Files**: None")

    # Scope drift detail
    drift = result.get("scope_status", {}).get("scope_drift") or []
    if drift:
        lines.append("- **Scope Drift Details** (Modified files outside allowed scope):")
        for f in drift:
            lines.append(f"  - `{f}`")

    # Violations detail
    violations = result.get("scope_status", {}).get("unauthorized_edits") or []
    if violations:
        lines.append("- **Unauthorized Edits Details** (Forbidden files modified):")
        for f in violations:
            lines.append(f"  - `{f}`")

    lines.extend([
        "",
        "## 3. Evidence Checklist",
        "",
        f"- **Required Evidence Met**: {not result.get('evidence_status', {}).get('has_missing', False)}",
    ])

    missing = result.get("evidence_status", {}).get("missing_evidence") or []
    if missing:
        lines.append("- **Missing Evidence Items**:")
        for m in missing:
            lines.append(f"  - `{m}`")

    found = result.get("evidence_status", {}).get("evidence_files") or []
    if found:
        lines.append("- **Found Evidence Files**:")
        for f in found:
            lines.append(f"  - `{f}`")

    lines.extend([
        "",
        "## 4. Test Validations",
        "",
    ])

    test_results = result.get("test_results")
    if test_results:
        passed = test_results.get("passed", True)
        passed_status = "PASSED" if passed else "FAILED"
        lines.extend([
            f"- **Test Status**: {passed_status}",
            f"- **Total Tests**: {test_results.get('total_count', 0)}",
            f"- **Failed Tests**: {test_results.get('failed_count', 0)}",
        ])
    else:
        lines.append("- **Test Status**: No test execution details available.")

    lines.extend([
        "",
        "## 5. Security & Governance Policies",
        "",
        f"- **Human Approval Required**: {result.get('human_approval_required', False)}",
        f"- **External Auto-execution Allowed**: {result.get('policy', {}).get('external_auto_execution_allowed', False)}",
        f"- **Phase Close Requires Evidence**: {result.get('policy', {}).get('phase_close_requires_evidence', True)}",
        "",
        "---",
        "*Report generated by AgentLab Phase Acceptance Engine.*",
    ])

    return "\n".join(lines)
