"""Safe GitHub sync manager — self-check → commit → push.

Never pushes blindly. Requires self-check pass first.
Writes sync_report.yml and updates 10_SYNC_LEDGER.yml.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from atomic_io import atomic_write_yaml, safe_read_yaml
from git_utils import commit, get_changed_files, is_inside_work_tree, push, stage_files
from rule_self_check import run_self_check


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def run_sync(
    agentlab_root: Path,
    project: str,
    task_id: str,
    *,
    dry_run: bool = False,
    confirm: bool = False,
    remote: str = "origin",
    branch: str = "main",
) -> dict:
    """Run self-check + guarded commit + push.

    Parameters:
        agentlab_root: repo root
        project: project name
        task_id: task id
        dry_run: don't actually commit/push
        confirm: skip confirmation prompt (for CLI --confirm)
        remote: git remote name
        branch: git branch name

    Returns sync_report dict.
    """
    run_dir = agentlab_root / "projects" / project / "runs" / task_id
    run_dir.mkdir(parents=True, exist_ok=True)

    report: dict = {
        "version": 1,
        "project": project,
        "task_id": task_id,
        "created_at": utc_now(),
        "status": "skipped",
        "remote": remote,
        "branch": branch,
        "commit_sha": "",
        "pushed": False,
        "self_check_report": "self_check_report.yml",
        "changed_files": [],
        "blocking_reasons": [],
        "warnings": [],
    }

    # ── 1. Run self-check ───────────────────────────────────────────────
    self_check = run_self_check(agentlab_root, project, task_id)
    report["changed_files"] = self_check.get("artifacts", {}).get("changed_files", [])
    report["blocking_reasons"] = self_check.get("blocking_reasons", [])

    if self_check["status"] == "fail":
        report["status"] = "failed"
        report["warnings"] = [f"Self-check failed: {len(self_check.get('blocking_reasons', []))} blocking issues."]
        _write_report(run_dir, report)
        return report

    if self_check["status"] == "warn" and not confirm:
        report["status"] = "skipped"
        report["warnings"] = ["Self-check warnings — use --confirm to proceed."]
        _write_report(run_dir, report)
        return report

    # ── 2. Git checks ────────────────────────────────────────────────────
    if not is_inside_work_tree(agentlab_root):
        report["status"] = "failed"
        report["blocking_reasons"].append("Not inside a git repository.")
        _write_report(run_dir, report)
        return report

    changed = get_changed_files(agentlab_root)
    if not changed:
        report["status"] = "skipped"
        report["warnings"].append("No changed files to commit.")
        _write_report(run_dir, report)
        return report

    # ── 3. Dry-run ───────────────────────────────────────────────────────
    if dry_run:
        report["status"] = "skipped"
        report["warnings"].append("Dry-run mode — no commit or push performed.")
        report["changed_files"] = changed
        _write_report(run_dir, report)
        return report

    # ── 4. Stage and commit ──────────────────────────────────────────────
    stage_files(agentlab_root, changed)

    short_slug = task_id.replace("task_", "").replace("_", "-")[:30]
    msg = (
        f"AgentLab: {task_id} {short_slug}\n\n"
        f"Project: {project}\n"
        f"Task: {task_id}\n"
        f"Self-check: {self_check['status']}\n"
        f"Changed files: {len(changed)}\n\n"
        f"Generated by AgentLab GitHub Sync Manager."
    )
    ok, sha = commit(agentlab_root, msg)
    if not ok:
        report["status"] = "failed"
        report["blocking_reasons"].append(f"Commit failed: {sha}")
        _write_report(run_dir, report)
        return report

    report["commit_sha"] = sha
    report["status"] = "committed_only"

    # ── 5. Push ──────────────────────────────────────────────────────────
    pushed_ok, push_msg = push(agentlab_root, remote, branch)
    if pushed_ok:
        report["status"] = "pushed"
        report["pushed"] = True
    else:
        report["status"] = "committed_only"
        report["warnings"].append(f"Push failed: {push_msg[:200]}")

    _write_report(run_dir, report)

    # ── 6. Update project sync ledger ────────────────────────────────────
    _update_sync_ledger(agentlab_root, project, report)

    return report


def _write_report(run_dir: Path, report: dict) -> None:
    atomic_write_yaml(run_dir / "sync_report.yml", report)


def _update_sync_ledger(root: Path, project: str, report: dict) -> None:
    ledger_path = root / "projects" / project / "agent_docs" / "10_SYNC_LEDGER.yml"
    ledger = safe_read_yaml(ledger_path) or {"version": 1, "project": project, "entries": []}

    entry = {
        "timestamp": report["created_at"],
        "task_id": report["task_id"],
        "status": report["status"],
        "remote": report["remote"],
        "branch": report["branch"],
        "commit_sha": report.get("commit_sha", ""),
        "self_check_status": report.get("status", "?"),
        "changed_files_count": len(report.get("changed_files", [])),
    }
    ledger.setdefault("entries", []).append(entry)
    atomic_write_yaml(ledger_path, ledger)