#!/usr/bin/env bash
set -uo pipefail

# Generated by AgentLab. Review before running.
# This script may send private project context through configured AgentLab role-session providers.
# Run it only from a trusted terminal/session that is allowed to execute Crown role-session acceptance smokes.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
REQUEST_PATH="$ROOT/acceptance_runs/agentlab_capability_acceptance/trusted_live_runner_request.yml"
STATUS_PATH="$ROOT/acceptance_runs/agentlab_capability_acceptance/trusted_live_runner_status.yml"
COLLECT_PATH="$ROOT/acceptance_runs/agentlab_capability_acceptance/trusted_live_runner_collect.yml"
READINESS_PATH=acceptance_runs/agentlab_capability_acceptance/internal_live_readiness.yml
PREFLIGHT_PATH="$ROOT/acceptance_runs/agentlab_capability_acceptance/trusted_live_runner_preflight.yml"
REQUEST_ID=trusted_live_20260712_0505_writer_contract_v1
LOG_DIR="$(dirname "$STATUS_PATH")/trusted_live_runner_logs"
RUN_LOG="$LOG_DIR/${REQUEST_ID}_$(date -u +%Y%m%dT%H%M%SZ).log"
mkdir -p "$LOG_DIR"
cd "$ROOT"
failures=0
health_failures=0
RUN_ONLY=""
TRUSTED_LIVE_RUNNER="${AGENTLAB_TRUSTED_LIVE_RUNNER:-}"
ROLE_SESSION_ACCEPTANCE_APPROVED="${AGENTLAB_ROLE_SESSION_ACCEPTANCE_APPROVED:-}"

if [ "${1:-}" = "--only" ]; then
  RUN_ONLY="${2:-}"
  if [ -z "$RUN_ONLY" ]; then
    echo "--only requires an item id" | tee -a "$RUN_LOG"
    exit 1
  fi
elif [ "${1:-}" != "" ] && [ "${1:-}" != "--preflight-only" ] && [ "${1:-}" != "--session-health-only" ]; then
  echo "unknown argument: ${1:-}" | tee -a "$RUN_LOG"
  exit 1
fi

require_command() {
  local command_name="$1"
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "missing required command: $command_name" | tee -a "$RUN_LOG"
    failures=$((failures + 1))
  fi
}

require_runtime_commands() {
  require_command agy
  require_command hermes
}

write_preflight_report() {
  ./agentlab.sh trusted-live-runner-preflight --request "$REQUEST_PATH" --out "$PREFLIGHT_PATH" >>"$RUN_LOG" 2>&1
}

require_trusted_live_runner_env() {
  if [ "$TRUSTED_LIVE_RUNNER" != "1" ]; then
    echo "refusing to run canonical session health or private role-session acceptance smoke without AGENTLAB_TRUSTED_LIVE_RUNNER=1" | tee -a "$RUN_LOG"
    echo "run from a trusted AgentLab runner or user terminal and prefix the command with AGENTLAB_TRUSTED_LIVE_RUNNER=1" | tee -a "$RUN_LOG"
    write_preflight_report || true
    exit 1
  fi
}

require_role_session_acceptance_approval_env() {
  if [ "$ROLE_SESSION_ACCEPTANCE_APPROVED" != "1" ]; then
    echo "refusing to send private Crown context without AGENTLAB_ROLE_SESSION_ACCEPTANCE_APPROVED=1" | tee -a "$RUN_LOG"
    echo "session health checks can use --session-health-only with AGENTLAB_TRUSTED_LIVE_RUNNER=1; role-session acceptance also requires explicit approval env" | tee -a "$RUN_LOG"
    write_preflight_report || true
    exit 1
  fi
}

collect_reports() {
  if [ -n "$RUN_ONLY" ]; then
    ./agentlab.sh trusted-live-runner-collect --request "$REQUEST_PATH" --out "$COLLECT_PATH" --item "$RUN_ONLY" >>"$RUN_LOG" 2>&1
  else
    ./agentlab.sh trusted-live-runner-collect --request "$REQUEST_PATH" --out "$COLLECT_PATH" >>"$RUN_LOG" 2>&1
  fi
}

trusted_status_value() {
  awk '/^status:/ { print $2; exit }' "$STATUS_PATH"
}

trusted_item_status_value() {
  python3 - "$STATUS_PATH" "$RUN_ONLY" <<'PY'
import sys
from pathlib import Path

import yaml

path = Path(sys.argv[1])
item_id = sys.argv[2]
try:
    report = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
except Exception:
    print("missing")
    raise SystemExit(0)
for item in report.get("items") or []:
    if isinstance(item, dict) and item.get("id") == item_id:
        print(item.get("status") or "missing")
        raise SystemExit(0)
print("missing")
PY
}

session_health_issue_count() {
  awk '
    /^session_health_issues: *\[\]/ { print 0; found=1; exit }
    /^session_health_issues:/ { in_section=1; found=1; next }
    in_section && /^[^[:space:]-]/ { print count + 0; in_section=0; exit }
    in_section && /^- / { count++ }
    END { if (in_section) print count + 0; else if (!found) print 1 }
  ' "$READINESS_PATH"
}

selected_session_health_issue_count() {
  if [ -z "$RUN_ONLY" ]; then
    session_health_issue_count
    return
  fi
  python3 - "$READINESS_PATH" "$RUN_ONLY" <<'PY'
import sys
from pathlib import Path

import yaml

path = Path(sys.argv[1])
item_id = sys.argv[2]
required_by_item = {
    "run_crown_internal_writer_eval": {"current_agy_session_health"},
    "run_crown_internal_media_smoke": {"current_grok_session_health"},
}
required = required_by_item.get(item_id)
if not required:
    print(1)
    raise SystemExit(0)
try:
    report = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
except Exception:
    print(1)
    raise SystemExit(0)
issues = report.get("session_health_issues") or []
if not isinstance(issues, list):
    print(1)
    raise SystemExit(0)
count = 0
for issue in issues:
    if isinstance(issue, dict) and issue.get("id") in required:
        count += 1
print(count)
PY
}

print_session_health_issues() {
  python3 - "$READINESS_PATH" <<'PY' | tee -a "$RUN_LOG"
import sys
from pathlib import Path

import yaml

path = Path(sys.argv[1])
try:
    report = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
except Exception as exc:
    print(f"session_health_issue_report_unreadable path={path} error={exc}")
    raise SystemExit(0)
issues = report.get("session_health_issues") or []
if not isinstance(issues, list):
    print(f"session_health_issue_report_malformed path={path}")
    raise SystemExit(0)
for index, issue in enumerate(issues, start=1):
    if not isinstance(issue, dict):
        print(f"session_health_issue[{index}] malformed={issue!r}")
        continue
    issue_id = issue.get("id") or "unknown"
    status = issue.get("status") or "unknown"
    reason = issue.get("reason") or "unspecified"
    next_action = issue.get("next_action") or "unspecified"
    print(
        f"session_health_issue[{index}] id={issue_id} "
        f"status={status} reason={reason} next_action={next_action}"
    )
PY
}

guard_clean_session_health() {
  local issue_count
  issue_count="$(selected_session_health_issue_count)"
  if [ "$issue_count" != "0" ]; then
    echo "relevant session health still has $issue_count issue(s); refusing to send private Crown context" | tee -a "$RUN_LOG"
    print_session_health_issues
    ./agentlab.sh trusted-live-runner-status --request "$REQUEST_PATH" --out "$STATUS_PATH" >>"$RUN_LOG" 2>&1 || true
    collect_reports || true
    echo "status_path=$STATUS_PATH" | tee -a "$RUN_LOG"
    echo "collect_path=$COLLECT_PATH" | tee -a "$RUN_LOG"
    exit 1
  fi
}

should_run_session_health_command() {
  local command_text="$1"
  if [ "$RUN_ONLY" = "run_crown_internal_writer_eval" ] && [[ "$command_text" == *"grok-cli-smoke"* ]]; then
    return 1
  fi
  if [ "$RUN_ONLY" = "run_crown_internal_media_smoke" ] && [[ "$command_text" == *"agy-cli-smoke"* ]]; then
    return 1
  fi
  return 0
}

run_session_health_checks() {
  echo "running non-private session health checks" | tee -a "$RUN_LOG"
  if should_run_session_health_command './agentlab.sh agy-cli-smoke --live --out acceptance_runs/agentlab_capability_acceptance/agy_cli_session_smoke.yml'; then
    bash -lc './agentlab.sh agy-cli-smoke --live --out acceptance_runs/agentlab_capability_acceptance/agy_cli_session_smoke.yml' >>"$RUN_LOG" 2>&1
    local code=$?
    echo './agentlab.sh agy-cli-smoke --live --out acceptance_runs/agentlab_capability_acceptance/agy_cli_session_smoke.yml' exit_code=$code | tee -a "$RUN_LOG"
    if [ "$code" -ne 0 ]; then
      health_failures=$((health_failures + 1))
    fi
  else
    echo './agentlab.sh agy-cli-smoke --live --out acceptance_runs/agentlab_capability_acceptance/agy_cli_session_smoke.yml' skipped_for_selected_item=$RUN_ONLY | tee -a "$RUN_LOG"
  fi
  if should_run_session_health_command './agentlab.sh grok-cli-smoke --live --out acceptance_runs/agentlab_capability_acceptance/grok_cli_session_smoke.yml'; then
    bash -lc './agentlab.sh grok-cli-smoke --live --out acceptance_runs/agentlab_capability_acceptance/grok_cli_session_smoke.yml' >>"$RUN_LOG" 2>&1
    local code=$?
    echo './agentlab.sh grok-cli-smoke --live --out acceptance_runs/agentlab_capability_acceptance/grok_cli_session_smoke.yml' exit_code=$code | tee -a "$RUN_LOG"
    if [ "$code" -ne 0 ]; then
      health_failures=$((health_failures + 1))
    fi
  else
    echo './agentlab.sh grok-cli-smoke --live --out acceptance_runs/agentlab_capability_acceptance/grok_cli_session_smoke.yml' skipped_for_selected_item=$RUN_ONLY | tee -a "$RUN_LOG"
  fi
  if should_run_session_health_command './agentlab.sh internal-live-readiness --out acceptance_runs/agentlab_capability_acceptance/internal_live_readiness.yml'; then
    bash -lc './agentlab.sh internal-live-readiness --out acceptance_runs/agentlab_capability_acceptance/internal_live_readiness.yml' >>"$RUN_LOG" 2>&1
    local code=$?
    echo './agentlab.sh internal-live-readiness --out acceptance_runs/agentlab_capability_acceptance/internal_live_readiness.yml' exit_code=$code | tee -a "$RUN_LOG"
    if [ "$code" -ne 0 ]; then
      health_failures=$((health_failures + 1))
    fi
  else
    echo './agentlab.sh internal-live-readiness --out acceptance_runs/agentlab_capability_acceptance/internal_live_readiness.yml' skipped_for_selected_item=$RUN_ONLY | tee -a "$RUN_LOG"
  fi
}

if [ ! -x ./agentlab.sh ]; then
  echo "missing executable ./agentlab.sh under $ROOT" | tee -a "$RUN_LOG"
  failures=$((failures + 1))
fi
if [ "${1:-}" = "--preflight-only" ]; then
  require_runtime_commands
  write_preflight_report || failures=$((failures + 1))
  echo "preflight_path=$PREFLIGHT_PATH" | tee -a "$RUN_LOG"
  exit "$failures"
fi

if [ "${1:-}" = "--session-health-only" ]; then
  require_trusted_live_runner_env
  require_runtime_commands
  if [ "$failures" -ne 0 ]; then
    write_preflight_report || true
    exit "$failures"
  fi
  run_session_health_checks
  guard_clean_session_health
  if [ "$health_failures" -ne 0 ]; then
    failures=$((failures + health_failures))
  fi
  echo "session_health_log=$RUN_LOG" | tee -a "$RUN_LOG"
  exit "$failures"
fi

require_trusted_live_runner_env
require_role_session_acceptance_approval_env
require_runtime_commands

if [ "$failures" -ne 0 ]; then
  echo "trusted live runner preflight failed; refreshing status" | tee -a "$RUN_LOG"
  write_preflight_report || true
  ./agentlab.sh trusted-live-runner-status --request "$REQUEST_PATH" --out "$STATUS_PATH" >>"$RUN_LOG" 2>&1 || true
  collect_reports || true
  exit 1
fi

run_session_health_checks
guard_clean_session_health
if [ "$health_failures" -ne 0 ]; then
  echo "trusted live runner session health commands failed; refreshing status" | tee -a "$RUN_LOG"
  ./agentlab.sh trusted-live-runner-status --request "$REQUEST_PATH" --out "$STATUS_PATH" >>"$RUN_LOG" 2>&1 || true
  collect_reports || true
  failures=$((failures + health_failures))
  exit 1
fi

run_item() {
  local item_id="$1"
  local command_text="$2"
  echo "running $item_id" | tee -a "$RUN_LOG"
  bash -lc "$command_text" >>"$RUN_LOG" 2>&1
  local code=$?
  echo "$item_id exit_code=$code" | tee -a "$RUN_LOG"
  if [ "$code" -ne 0 ]; then
    failures=$((failures + 1))
  fi
}

should_run_item() {
  local item_id="$1"
  if [ -z "$RUN_ONLY" ] || [ "$RUN_ONLY" = "$item_id" ]; then
    return 0
  fi
  return 1
}

selected_item_ran=0

# run_crown_internal_writer_eval -> Writer / agy
if should_run_item run_crown_internal_writer_eval; then
  selected_item_ran=1
  run_item run_crown_internal_writer_eval './agentlab.sh narrative-eval run --project Crown_of_Ash --suite crown_live_single_chapter_probe_20260707 --mode live --chapters 1 --timestamp trusted_live_20260712_0505_writer_contract_v1_writer --writer-worker agy'
fi

# run_crown_internal_media_smoke -> ArtifactProducer / grok
if should_run_item run_crown_internal_media_smoke; then
  selected_item_ran=1
  run_item run_crown_internal_media_smoke './agentlab.sh media-backend-execute --contract projects/Crown_of_Ash/runs/task_probe_crown_comic_video_poster_series_scaffold_20260707/media_generation_contract.yml --out-dir projects/Crown_of_Ash/runs/task_probe_crown_comic_video_poster_series_scaffold_20260707/artifacts/media_backend_live_internal_trusted_live_20260712_0505_writer_contract_v1_media --live --role ArtifactProducer --worker grok --project Crown_of_Ash --run-id task_probe_crown_comic_video_poster_series_scaffold_20260707'
fi

if [ -n "$RUN_ONLY" ] && [ "$selected_item_ran" -ne 1 ]; then
  echo "unknown trusted live item: $RUN_ONLY" | tee -a "$RUN_LOG"
  failures=$((failures + 1))
fi
echo "refreshing trusted live runner status" | tee -a "$RUN_LOG"
./agentlab.sh trusted-live-runner-status --request "$REQUEST_PATH" --out "$STATUS_PATH" >>"$RUN_LOG" 2>&1
status_code=$?
if [ "$status_code" -ne 0 ]; then
  failures=$((failures + 1))
fi
echo "collecting trusted live runner reports" | tee -a "$RUN_LOG"
collect_reports
collect_code=$?
if [ "$collect_code" -ne 0 ]; then
  failures=$((failures + 1))
fi
trusted_status="$(trusted_status_value)"
echo "trusted_live_runner_status=$trusted_status" | tee -a "$RUN_LOG"
if [ -n "$RUN_ONLY" ]; then
  selected_status="$(trusted_item_status_value)"
  echo "trusted_live_runner_item_status[$RUN_ONLY]=$selected_status" | tee -a "$RUN_LOG"
  if [ "$selected_status" != "pass" ]; then
    echo "selected trusted live item is not accepted; item status must be pass" | tee -a "$RUN_LOG"
    failures=$((failures + 1))
  fi
elif [ "$trusted_status" != "pass" ]; then
  echo "trusted live runner artifacts are not accepted; status must be pass" | tee -a "$RUN_LOG"
  failures=$((failures + 1))
fi
echo "status_path=$STATUS_PATH" | tee -a "$RUN_LOG"
echo "collect_path=$COLLECT_PATH" | tee -a "$RUN_LOG"
echo "run_log=$RUN_LOG" | tee -a "$RUN_LOG"
if [ "$failures" -ne 0 ]; then
  exit 1
fi